# Generated by Django 3.2.8 on 2021-10-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210930_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='Command',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='Output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='TransferLog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.filetransferlog'),
        ),
    ]
