# Generated by Django 3.2.8 on 2021-10-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211008_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransferlog',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
