# Generated by Django 3.2.8 on 2021-10-15 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_filetransferlog_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransferlog',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='Queued',
            field=models.BooleanField(default=True),
        ),
    ]
