# Generated by Django 3.2.8 on 2021-11-03 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211015_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
